from .__version__ import __description__, __title__, __version__
from .api import delete, get, head, options, patch, post, put, request, stream
from .auth import BasicAuth, DigestAuth
from .client import AsyncClient, Client
from .config import TimeoutConfig  # For 0.8 backwards compat.
from .config import PoolLimits, Proxy, Timeout
from .dispatch.proxy_http import HTTPProxy, HTTPProxyMode
from .exceptions import (
    ConnectionClosed,
    ConnectTimeout,
    CookieConflict,
    DecodingError,
    HTTPError,
    InvalidURL,
    NotRedirectResponse,
    PoolTimeout,
    ProtocolError,
    ProxyError,
    ReadTimeout,
    RedirectLoop,
    RequestBodyUnavailable,
    RequestNotRead,
    ResponseClosed,
    ResponseNotRead,
    StreamConsumed,
    TimeoutException,
    TooManyRedirects,
    WriteTimeout,
)
from .models import URL, Cookies, Headers, QueryParams, Request, Response
from .status_codes import StatusCode, codes

__all__ = [
    "__description__",
    "__title__",
    "__version__",
    "delete",
    "get",
    "head",
    "options",
    "patch",
    "post",
    "patch",
    "put",
    "request",
    "stream",
    "codes",
    "AsyncClient",
    "BasicAuth",
    "Client",
    "DigestAuth",
    "PoolLimits",
    "Proxy",
    "Timeout",
    "TimeoutConfig",  # For 0.8 backwards compat.
    "HTTPProxy",
    "HTTPProxyMode",  # For 0.8 backwards compat.
    "ConnectTimeout",
    "CookieConflict",
    "ConnectionClosed",
    "DecodingError",
    "HTTPError",
    "InvalidURL",
    "NotRedirectResponse",
    "PoolTimeout",
    "ProtocolError",
    "ReadTimeout",
    "RedirectLoop",
    "RequestBodyUnavailable",
    "ResponseClosed",
    "ResponseNotRead",
    "RequestNotRead",
    "StreamConsumed",
    "ProxyError",
    "TooManyRedirects",
    "WriteTimeout",
    "URL",
    "StatusCode",
    "Cookies",
    "Headers",
    "QueryParams",
    "Request",
    "TimeoutException",
    "Response",
    "DigestAuth",
]
