#!/bin/sh -e

export SOURCE_FILES="httpx tests"

set -x

./scripts/sync-version

echo "==> Checking formatting…"
uv run ruff format $SOURCE_FILES --diff

echo "==> Running type checks and linting…"
uv run mypy $SOURCE_FILES

echo "==> Running linting checks…"
uv run ruff check $SOURCE_FILES
