#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="httpx tests"

set -x

if [ -d 'pyodide']; then
    IGNORE_ARGS=""
else
    # if we don't have a pyodide environment set up, then don't test coverage 
    # for the emscripten transport
    IGNORE_ARGS="--omit=httpx/_transports/emscripten.py "
fi

${PREFIX}coverage combine || true
${PREFIX}coverage report ${IGNORE_ARGS} --show-missing --skip-covered --fail-under=100
