#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="httpx tests"

set -x

if [ -d 'pyodide_dist' ]; then
    IGNORE_ARGS="--omit=venv/*"
else
    # if we don't have a pyodide environment set up, then don't test coverage 
    # for the emscripten transport
    IGNORE_ARGS="--omit=httpx/_transports/emscripten.py,tests/emscripten/*,venv/*"
fi

${PREFIX}coverage combine 
${PREFIX}coverage report ${IGNORE_ARGS} --show-missing --skip-covered --fail-under=100
