#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}autoflake --in-place --recursive http3 tests
${PREFIX}black http3 tests
${PREFIX}isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply http3 tests
${PREFIX}mypy http3 --ignore-missing-imports --disallow-untyped-defs

scripts/clean
