#!/bin/sh -e

export PACKAGE="httpcore"
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov tests --cov ${PACKAGE} ${@}
${PREFIX}coverage report --show-missing --skip-covered --fail-under=100
